<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_layoutHelper = $this->helper('Ktpl\CategoryView\Helper\Layout');
$_dataHelper = $this->helper('Ktpl\CategoryView\Helper\Data');
?>
<?php $listingBlockItems = $_layoutHelper->getListingBlockItems(); ?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
	    $viewMode = 'list';
	    $image = 'category_page_list';
	    $showDescription = true;
	    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	    /**
	     * Position for actions regarding image size changing in vde if needed
	     */
	    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                
                <?php while(array_key_exists($iterator, $listingBlockItems)): ?>
                    <li class="item product product-item custom-section">
                    <?php echo $_layoutHelper->filterOutputHtml($listingBlockItems[$iterator], $block->getLayout()); ?>
                    </li>
                    <?php $iterator++; ?>
                <?php endwhile; ?>

                <?php $iterator++; ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-grid" id="product-item-info-<?php echo $_product->getId()?>">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>

                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        
                        <div class="image-container">
                            <div class="product-labels">
                                <?php if($_product->getIsNewProduct()): ?>
                                    <div class="label new"><?php /* @escapeNotVerified */ echo __('New'); ?></div>
                                <?php endif; ?>
                                <?php if($_product->getIsSaleProduct()): ?>
                                    <div class="label sale"><?php /* @escapeNotVerified */ echo __('Sale'); ?></div>
                                <?php endif; ?>
                            </div>

                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>                           
                            </a>
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>                       
                                
                            </div>
                            <div class="dinner-configurable-options">
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
							<?php //if($_product->getTypeId() == "configurable"):?>
							<?php echo $block->getProductDetailsHtml($_product); ?>
                            </div>
                            <div class="dinner-configurable-options-mobile" style="display: none">
                               
                                <?php /* @escapeNotVerified */ echo $_product->getSetsPrice() ?>
                            </div>
						  <?php //endif;?>
                        </div>
                        </div>
                        <div class="product details product-item-details" id="product-item-detail-<?php echo $_product->getId()?>">                            
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            
                            <span class="check-range-text">
                                <a class="clickable" data-product-id="<?php echo $_product->getId()?>" target="_top" data-target="#price-range-modal" data-toggle="modal"><?php echo __("Check range and prices")?></a>
                           </span>
    						<?php if ($showDescription):?>
    							<div class="product description product-item-description">
    								<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
    								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
    								   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
    							</div>
    						<?php endif; ?>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>     
                        </div>
                </li>
            <?php endforeach; ?>
        </ol>
        <div class="mobile-product-item-popup">
            <div class="mobile-popup-inner">
            <a href="javascript:void(0)" class="close-popup"><i aria-hidden="true" class="fa fa-times"></i></a>
            <div class="mobile-popup-product-image"></div>
            <div class="mobile-popup-product-name"></div>
            <div class="mobile-popup-product-options"></div>
         </div>
        </div>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script>
    require([
        'jquery'
    ], function($) {
        $(function(){
            $("body").addClass("<?php echo __('category-dinnerware');?>");

            $(".close-popup").click(function() {
                $(".product-item-info").removeClass("active-popup-mobile");
                $(".mobile-product-item-popup").removeClass("show");
                $(".mobile-product-item-popup .mobile-popup-product-image").html("");
                $(".mobile-product-item-popup .mobile-popup-product-name").html("");
                $(".mobile-product-item-popup .mobile-popup-product-options").html("");
                $("body").removeClass("modal-open");
            });

            $(".clickable").click(function() {
                var pid = $(this).attr("data-product-id");
                $(".product-item-info").removeClass("active-popup-mobile");
                $(".mobile-product-item-popup .mobile-popup-product-image").html("");
                $(".mobile-product-item-popup .mobile-popup-product-name").html("");
                $(".mobile-product-item-popup .mobile-popup-product-options").html("");

                $("#product-item-info-"+pid).addClass("active-popup-mobile");
                $("body").addClass("modal-open");
                $(".mobile-product-item-popup").addClass("show");

                $("#product-item-info-"+pid +" .product-image-container").clone().appendTo(".mobile-product-item-popup .mobile-popup-product-image");
                console.log($("#product-item-info-"+pid +" .product-item-details").html());
                $("#product-item-detail-"+pid +" .product-item-name").clone().appendTo(".mobile-product-item-popup .mobile-popup-product-name");
                $("#product-item-info-"+pid +" .dinner-configurable-options-mobile").clone().appendTo(".mobile-product-item-popup .mobile-popup-product-options");
                $(".mobile-product-item-popup .mobile-popup-product-options .dinner-configurable-options-mobile").show();
            })

            var formHiddenInput = $('<input />').attr({
            	'type': 'hidden',
            	'name': 'option-id'
            });

            var formToSubmit = $('<form></form>').attr({
            	'method': 'POST',
            }).append(formHiddenInput);

            $("body").append(formToSubmit);

            $('.dinner-configurable-options > .option-title-box .option-title').click(function() {
            	formHiddenInput.val($(this).attr('data-option-id'));
            	formToSubmit.attr({'action': $(this).attr('data-url')}).submit();
            });
        });
    });
</script>