<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="storage-product-info-add-to-cart">
    <div class="product-details">
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Pick quantity:') ?></span></label>
                    <div class="control">
                    	<div class="qty-wrapper">
                    		<div class="qty-trigger"><?php /* @escapeNotVerified */ echo __('%1 Set', ($block->getProductDefaultQty() * 1)); ?></div>
                    		<div class="qty-options">
                    			<?php for($i = 1; $i <= 10; $i++): ?>
                    				<div class="options" data-value="<?php echo $i; ?>">
                    					<?php echo __('%1 Set', $i); ?>
                					</div>
                				<?php endfor; ?>
                    		</div>
                    	</div>
                        <input type="hidden"
                        	name="qty"
                           	id="qty"
                           	value="<?php /* @escapeNotVerified */ echo ($block->getProductDefaultQty() * 1); ?>"
                           	title="<?php /* @escapeNotVerified */ echo __('Pick Quantity') ?>" class="input-text qty"
                           	data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                    </div>
                </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($) {
        $(function(){
            $("body").addClass("<?php echo __('product-detail-storage');?>");

            $(document).on("click", function(event){
                if ($(event.target).next(".swatch-attribute-options").find('.swatch-option').size() < 1) {
                    $('.swatch-select-wrapper .swatch-attribute-options').hide();
                }
                if($(event.target).next(".qty-options").find('.options').size() < 1)
                {
                    $('.qty-wrapper .qty-options').hide();
                }
            });
        })
    });
</script>