<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
$productHelper = $this->helper('Ktpl\ProductView\Helper\Data');
$optionId = $this->getRequest()->getPost('option-id');
$_layoutHelper = $this->helper('Ktpl\ProductView\Helper\Layout');
$listingBlockItems = $_layoutHelper->getListingBlockItems();
?>
<?php $options = $block->decorateArray($block->getOptions()); ?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
        <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "priceBundle": {
                        "optionConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>,
                        "controlContainer": ".field.option"
                    }
                }
            }
        </script>
        <fieldset class="fieldset fieldset-bundle-options">
            <h4>Scroll down to see what the set consists of:</h4>
            <legend id="customizeTitle" class="legend title">
                <span><?php /* @escapeNotVerified */ echo __('Customize %1', $helper->productAttribute($product, $product->getName(), 'name')) ?></span>
            </legend>
            <?php echo $block->getChildHtml('product_info_bundle_options_top');?>

            <?php $optionValues = $productHelper->getBundleProducts($options); ?> 
            <div class="bundle-options-container">
                <ul class="bundle-options-title-wrapper">
                    <?php $i = 0;?>
                    <?php foreach($optionValues['options'] as $option): ?>
                        <li data-id="bundle-option-<?php /* @escapeNotVerified */ echo $option['id']; ?>" class="bundle-option-title" data-product-ids="<?php echo implode(",", $option['product_ids']) ?>">
                            <span><?php echo $block->escapeHtml($option['title']) ?><em class="option-label">: <?php echo $block->escapeHtml($option['option_label']) ?> </em></span>
                            
                        </li>
                    <?php endforeach; ?>
                </ul>
                 <div class="bundle-options-title-select-box">
                <select class="bundle-options-title-select">
                    <?php foreach($optionValues['options'] as $option): ?>
                        <option data-id="bundle-option-<?php /* @escapeNotVerified */ echo $option['id']; ?>" class="bundle-option-title" data-product-ids="<?php echo implode(",", $option['product_ids']) ?>" value="<?php echo $block->escapeHtml($option['title']) ?>">
                            <?php echo $block->escapeHtml($option['title'] . ": " . $option['option_label']) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
                <div class="bundle-options-associated-products-wrapper">
                    <?php $iterator = 1; ?>
                    <?php $setBLock = false; ?>
                    <?php foreach($optionValues['product_ids'] as $productId): ?>
                        <?php while(array_key_exists($iterator, $listingBlockItems)): ?>
                            <?php $setBLock = true; ?>
                            <div class="bundle-associated-product bundle-product custom-section">
                            <?php echo $_layoutHelper->filterOutputHtml($listingBlockItems[$iterator], $block->getLayout()); ?>
                            </div>
                            <?php $iterator++; ?>
                        <?php endwhile; ?>

                        <?php $iterator++; ?>
                        <div class="bundle-associated-product bundle-product-<?php echo $productId ?>" >
                            <?php $_product = $productHelper->getProduct($productId); ?> 

                             <div class="product-item-info" data-container="product-grid">
                                <?php $productImage = $productHelper->getImage($_product, 'related_products_list'); ?>
                                <?php echo $productImage->toHtml(); ?>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo __($_product->getName()); ?>
                                        </a>
                                    </strong>
									<div class="dimension-value">							
										<?php /* @escapeNotVerified */ echo __($_product->getDinnerwareSize()) ?>
									</div>
                                </div>
								<div class="overlay"></div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <?php if($setBLock == false):?>
                        <?php foreach ($listingBlockItems as $key => $listingBlockItem):?>
                            <?php $setBLock = true; ?>
                            <?php $column = (6 - ($key % 5));?>
                            <div class="bundle-associated-product bundle-product custom-section column<?php echo $column;?>">
                            <?php echo $_layoutHelper->filterOutputHtml($listingBlockItem, $block->getLayout()); ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endif;?>
                </div>
            </div>

            <script>
                require([
                    "jquery"
                ], function($) {
                    $(document).ready(function() {
                        $('.bundle-option-title').click(function() {

                            $(".bundle-option-title").removeClass("selected");
                            $(this).addClass("selected");

                            var bundleOptionId = $(this).attr('data-id');
                            var productIds = $(this).attr('data-product-ids').split(",");

                            $(".bundle-associated-product").removeClass("selected");
                            $(productIds).each(function(index, element) {
                                $(".bundle-product-" + element).addClass("selected");
                            });

                            $(".bundle-actual-options select > option").each(function() {
                                $(this).prop('selected', false);
                            });

                            $(".bundle-actual-options select").trigger("change");

                            $("#" + bundleOptionId + " > option").each(function() {
                                if($(this).attr('value') != "")
                                    $(this).prop('selected', true);
                            });    

                            $("#" + bundleOptionId ).trigger("change");
                        });
                        $('.bundle-options-title-select').change(function() {
                            var selectedOption = $(".bundle-options-title-select option:selected").attr("data-id");
                            $(".bundle-options-title-wrapper li[data-id="+selectedOption).trigger('click');
                        });

                        <?php if(isset($optionId) && !is_null($optionId)): ?>
                            var posted_element = $(".bundle-option-title[data-id='bundle-option-<?php echo $optionId; ?>']");
                            if(posted_element != undefined)
                                posted_element.trigger("click")
                            else
                                $(".bundle-option-title:first").trigger("click");
                        <?php else: ?>
                            $(".bundle-option-title:first").trigger("click");
                        <?php endif; ?>
                    });
                });
            </script>

            <div class="bundle-actual-options">
                <?php foreach ($options as $option): ?>
                    <?php if (!$option->getSelections()): ?>
                        <?php continue; ?>
                    <?php endif; ?>
                    <?php echo $block->getOptionHtml($option) ?>
                <?php endforeach; ?>
            </div>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?php /* @escapeNotVerified */ echo __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
