<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block block-recent-orders">
    <?php $_orders = $block->getOrders(); ?>
    <div class="block-content">
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <?php foreach ($_orders as $_order): ?>
                <div class="order-block">
                    <div class="left-block">
                        <div class="top-row">
                            <div class="order-number">
                                <strong><?php echo __('Order Number:'); ?></strong>
                                <?php echo __($_order->getRealOrderId()); ?>
                            </div>
                            <div class="order-date">
                                <strong><?php echo __('Order Placed On:'); ?></strong>
                                <?php echo __($_order->getCreatedAt()); ?>
                            </div>
                        </div>
                        <div class="bottom-row">
                            <div class="order-field">
                                <strong><?php echo __('Order Total'); ?></strong>
                                <label><?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?></label>
                            </div>
                            <div class="order-field">
                                <strong><?php echo __('Status'); ?></strong>
                                <label><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></label>
                            </div>
                            <div class="order-field">
                                <strong><?php echo __('Shipped To:'); ?></strong>
                                <address><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
                            </div>

                            <div class="order-actions">
                                <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                    $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                        ->getPostData($block->getReorderUrl($_order))
                                    ?>' class="action order">
                                        <span><?php /* @escapeNotVerified */ echo __('Repeat Your Order') ?></span>
                                    </a>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                    <div class="right-block">
                        <?php $_items = $_order->getItemsCollection(); ?>
                        <?php $_count = $_items->count(); ?>
                        <div class="items-wrapper owl-carousel">
                            <?php foreach ($_items as $_item): ?>
                                <?php if ($_item->getParentItem()): ?>
                                    <?php continue; ?>
                                <?php endif; ?>
                                <div class="item">
                                    <div class="image">
                                        <?php echo $block->getImage($_item->getProduct(), 'cart_page_product_thumbnail')->toHtml(); ?>
                                    </div>
                                    <div class="name"><?php echo $block->escapeHtml($_item->getName()) ?></div>
                                    <?php $attributes = ['volume']; ?>
                                    <div class="attributes">
                                        <?php foreach($attributes as $attribute): ?>
                                            <?php $attributeText = $_item->getProduct()->getAttributeText($attribute);?>
                                            <?php if(isset($attributeText) && $attributeText != ""): ?>
                                                <span><?php echo $attributeText; ?></span>
                                            <?php elseif($attributeText = $_item->getProduct()->getData($attribute)): ?>
                                                <span><?php echo $attributeText; ?></span>
                                            <?php endif; ?>    
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class="past-orders" style="display: none;">
            	<a href="javascript:void(0);" id="view-past-orders"><?php echo __('View Past Orders'); ?></a>
            </div>
        <?php else: ?>
            <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no orders.'); ?></span></div>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
	require([
		"jquery"
	], function ($) {
		$(document).ready(function() {
			$(".block-recent-orders .right-block .items-wrapper .owl-item").css({'transform' : 'rotate(-90deg)','-ms-transform' : 'rotate(-90deg)','-webkit-transform' : 'rotate(-90deg)'});				
			$(".block-recent-orders .right-block .items-wrapper").css({'transform' : 'rotate(90deg)','-ms-transform' : 'rotate(90deg)','-webkit-transform' : 'rotate(90deg)'});				
			
		});
	});
</script>
<script>
	require(['jquery', 'OwlCarousel'], function($){
		$(function(){
				$('.block-recent-orders .items-wrapper').owlCarousel({
					"autoplay": false,
					"items": 1,
					"nav": true,
					"dots": false,
					"loop": true,                    
				})

			$(".block-testimonial-slider .block-content").css("display","block");
			$(".block-testimonial-slider #loading").css("display","none");
		})
	});
</script>
