<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block account-nav">
    <nav class="account-nav">
        <ul class="nav items">
            <?php echo $block->getChildHtml();?>
        </ul>
    </nav>
</div>
