<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Ktpl\Blog\Block\Sidebar\Rss
 */
?>
<div class="widget block block-rss" data-bind="scope: 'blog-rss'">
    <div class="block-title">
        <img class="rss-icon" src="<?php echo $block->getViewFileUrl('Ktpl_Blog::images/rss-icon.png') ?>" alt="<?php echo __('RSS Feed') ?>" >
        <strong><a target="_blan" href="<?php echo $this->getUrl('blog/rss/feed') ?>"><?php echo __('RSS Feed') ?></a></strong>
    </div>
</div>