<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales v4.x.x
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/*
var_dump($this->splashPage->getEnabledLaunchingSoon());
var_dump($this->splashPage->getData()); exit;*/

?>

<div class="account-forgot prpop-account-forgot block-container" data-container="forgot" style="display: none;">
	<form action="<?php echo $block->getUrl('prprivatesale/splashpage/forgotpasswordpost') ?>" method="post" id="forgot-form">
		<div class="prpop-formholder">
			<div class="form-top-logo">
		        <img src="<?php echo $block->getLogoSrc(); ?>" alt="<?php echo $block->getLogoAlt() ?>" class="large" />
			</div>

			<h2><?php echo __('Retrieve your password here') ?></h2>
			<p><?php echo __('Please enter your email address below. You will receive a link to reset your password.') ?></p>

			<div class="prpop-cf">
				<div class="prpop-columb">
					<ul class="form-list prpop-form-list">
						<li>
							<label for="email_address" class="required"><em>*</em><?php echo __('Email Address') ?></label>
							<div class="input-box">
								<input type="text" name="email" alt="email" id="email_address_f" class="input-text required-entry validate-email" value="<?php echo $block->getEmailValue() ?>" placeholder="<?php echo __('Email Address') ?>" />
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>

        <div class="prpop-buttons-set prpop-cf">
			<div class="prpop-back-hld prpop-desktop">
				<?php if (!$this->splashPage->getEnabledLaunchingSoon()): ?>
					 <a href="#" data-role="change-form" data-show="login" class="backtologin"><?php echo __('Back to login page');?></a>
				<?php else: ?>
					<a href="#" data-role="change-form" data-show="register" class="backtologin"><?php echo __('Back to registration page');?></a>
				<?php endif; ?>
			</div>
            <button type="submit" title="<?php echo __('Submit') ?>" class="button prpop-button prpop-btn-proceed-checkout"><span class="holder"><span><?php echo __('Submit') ?></span></span></button>
			<div class="prpop-ajax-loader-wrapper">
				<img class="prpop-ajax-loader" src="<?php echo $block->getViewFileUrl('Plumrocket_PrivateSale::images/loader.gif');?>" alt="loader">
			</div>
        </div>
	</form>

</div>
<!--success forgot-->
<div class="forgot-success succes-block block-container" data-container="forgot-success" style="display: none;">
	<div class="prpop-forgot-success prpop-succes-block">
		<div class="prpop-formholder">
			<div class="form-top-logo">
		        <img src="<?php echo $block->getLogoSrc(); ?>" alt="<?php echo $block->getLogoAlt() ?>" class="large" />
			</div>
			<h2><?php echo __('New password has been sent');?></h2>
			<p id="forgot_text"><?php echo __('If there is an account associated with <span class="email"></span> you will receive an email with a link to reset your password.') ?>
				<br /><br />
			</p>
			<p>
				<?php if (!$this->splashPage->getEnabledLaunchingSoon()): ?>
					<a href="#" data-role="change-form" data-show="login" class="backtologin"><?php echo __('Back to login page');?></a>
				<?php else: ?>
					<a href="#" data-role="change-form" data-show="register" class="backtologin"><?php echo __('Back to registration page');?></a>
				<?php endif; ?>
			</p>
		</div>
	</div>
</div>
