<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales v4.x.x
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php if ($this->showRegistrationForm()): ?>
<div class="account-create prpop-account-create block-container" data-container="register" <?php if (!$block->splashPage->getEnabledLaunchingSoon()): ?> style="display: none;" <?php endif; ?>>

	<div class="form-top-logo">
        <img src="<?php echo $block->getLogoSrc(); ?>" alt="<?php echo $block->getLogoAlt() ?>" class="large" />
	</div>
    <?php echo $block->getChildHtml('customer_form_register'); ?>
</div>
<?php endif; ?>


<?php $showSuccessBlock = !$this->showRegistrationForm() && $block->splashPage->getEnabledLaunchingSoon(); ?>

<!-- Success blocks -->
<div class="reg-success succes-block block-container" data-container="reg-success" <?php if (!$showSuccessBlock): ?> style="display:none;" <?php endif; ?>>
	<div class="hld prpop-reg-success prpop-succes-block">
		<div class="prpop-formholder">
			<div class="form-top-logo">
		        <img src="<?php echo $block->getLogoSrc(); ?>" alt="<?php echo $block->getLogoAlt() ?>" class="large" />
			</div>

			<?php if (!$block->splashPage->getEnabledLaunchingSoon()): ?>
				<h2><?php echo __('YOUR REQUEST HAS BEEN SUBMITTED'); ?></h2>
				<p><?php echo __('Thank you for you interest in Private Sale Store.'); ?> <br />
				<br /><?php echo __('We will notify you by email regarding your request for membership.'); ?> </p>
			<?php else: ?>
				<?php echo $block->filter($block->splashPage->getLaunchingText()); ?>
			<?php endif; ?>
		</div>
	</div>
</div>
