<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="drinkware-product-info-add-to-cart">
    <div class="product-details">
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Pick Quantity:') ?></span></label>
                    <div class="control">
                    	<?php if($_product->getViewLayout()):?>
                        <select name="qty"
                               id="qty"
                               title="<?php /* @escapeNotVerified */ echo __('Pick Quantity') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                           	<?php for($i = 1; $i <= 10; $i++): ?>
                           		<option value="<?php echo $i; ?>" <?php /* @escapeNotVerified */ echo (($block->getProductDefaultQty() * 1) == $i? 'selected="selected"': ''); ?>>
                           			<?php echo __('%1 Set', $i); ?>
                       			</option>
                           	<?php endfor; ?>
                       </select>
                   <?php endif;?>
                    </div>
                </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
