<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()):?>
    <div class="bundle-actions">
        <button id="bundle-slide-add-to-cart"
                class="action primary customize"
                type="button">
            <span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
        </button>
    </div>
<?php endif;?>
<script>
    require([
    	'jquery'
	], function($) {
		$('#bundle-slide-add-to-cart').bind('click', function(event) {
  			$(".box-tocart .action.tocart").trigger('click');
  		});
    });
</script>
