<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
USAGE:

Simple:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/

/**
 * @see \Magento\Customer\Block\Widget\Dob
 */
?>
<?php
$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?php /* @escapeNotVerified */ echo $fieldCssClass; ?>">
    <div class="field-display">
        <label class="label">
            <span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span>
        </label>
        <div class="control">
            <label class="value">
                <?php /* @escapeNotVerified */ echo $block->getValue() ?>
            </label>
        </div>
        <div class="field-edit">
            <a href="#" class="edit-field"><?php echo __('Edit') ?></a>
        </div>
    </div>
    <div class="field-actual">
        <label class="label" for="<?php echo $block->getHtmlId()?>">
            <span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span>
        </label>
        <div class="control customer-dob">
            <?php echo $block->getFieldHtml(); ?>
        </div>
        <div class="field-edit">
            <a href="#" class="save-field"><?php echo __('Save') ?></a>
            <a href="#" class="cancel-field"><?php echo __('Cancel') ?></a>
        </div>
    </div>
</div>
