<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
USAGE:

Simple:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->toHtml() ?>

For checkout/onepage/shipping.phtml:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->setFieldIdFormat('shipping:%s')
   ->setFieldNameFormat('shipping[%s]')
   ->setFieldParams('onchange="shipping.setSameAsBilling(false);"')
   ->toHtml() ?>
*/
/* @var $block \Magento\Customer\Block\Widget\Name */
$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
?>

<div class="field field-name-firstname required">
    <div class="field-display">
        <label class="label">
            <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?></span>
        </label>
        <div class="control">
            <label class="value"><?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?></label>
        </div>
        <div class="field-edit">
            <a href="#" class="edit-field"><?php echo __('Edit') ?></a>
        </div>
    </div>
    <div class="field-actual">
        <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>">
            <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?></span>
        </label>
        <div class="control">
            <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>" name="<?php /* @escapeNotVerified */ echo $block->getFieldName('firstname') ?>" value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>" title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>" class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('firstname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
        </div>
        <div class="field-edit">
            <a href="#" class="save-field"><?php echo __('Save') ?></a>
            <a href="#" class="cancel-field"><?php echo __('Cancel') ?></a>
        </div>
    </div>
</div>

<div class="field field-name-lastname required">
    <div class="field-display">
        <label class="label">
            <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?></span>
        </label>
        <div class="control">
            <label class="value"><?php echo $block->escapeHtml($block->getObject()->getLastname()) ?></label>
        </div>
        <div class="field-edit">
            <a href="#" class="edit-field"><?php echo __('Edit') ?></a>
        </div>
    </div>
    <div class="field-actual">
        <label class="label"  for="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>">
            <span><?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?></span>
        </label>
        <div class="control">
            <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>" name="<?php /* @escapeNotVerified */ echo $block->getFieldName('lastname') ?>" value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>" title="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>" class="input-text <?php /* @escapeNotVerified */ echo $block->getAttributeValidationClass('lastname') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
        </div>
        <div class="field-edit">
            <a href="#" class="save-field"><?php echo __('Save') ?></a>
            <a href="#" class="cancel-field"><?php echo __('Cancel') ?></a>
        </div>
    </div>
</div>