<?php $testimonials = $this->getItemCollection(); ?>
<div id="testimonials">
    <div id="loading" style="text-align: center; padding:40px 0 40px 0">
        <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
             alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
             >
    </div>
    <div id="owlslider" class="block-content owl-carousel" style="display: none">
        <?php foreach ($testimonials as $testimonial):?>
            <div class="item">
                <div class="customer-name">
                    <?php 
                        $date = date("jS M, Y", strtotime($testimonial->getDate())); 
                    ?>
                    <span class="name"><?php /* @escapeNotVerified */ echo __($testimonial->getName()) . " / " . $date;?></span> 
                </div>
                <div class="testimonial-title">
                    <span class="title"><?php /* @escapeNotVerified */ echo __($testimonial->getTitle());?></span> 
                </div>
                <div class="testimonial-description">
                    <span class="description"><?php /* @escapeNotVerified */ echo __($testimonial->getDescription());?></span> 
                </div>
            </div>
        <?php endforeach; ?>      
  </ul> 
</div>
<script>
    require(['jquery', 'OwlCarousel'], function($){
        $(function(){
                $('#owlslider').owlCarousel({
                    "autoplay": true,
                    "autoplayTimeout":3000,
                    "items": 3,
					"autoplaySpeed":300,
					"navSpeed":300,
                    "nav": true,
                    "loop": true,
                    "center":false,
                    "responsive":
                    {
						0:{
                            items:1
                        },						
                        768:{
                            items:2
                        },
                        1199:{
                            items:3
                        }
                    }
                })

            $(".block-testimonial-slider .block-content").css("display","block");
            $(".block-testimonial-slider #loading").css("display","none");
        })
    });
</script>
