<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template For Drinkware Glass
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_dataHelper = $this->helper('Ktpl\CategoryView\Helper\Data');
$_dataHelper->setCategorySortAttribute();
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_layoutHelper = $this->helper('Ktpl\CategoryView\Helper\Layout');
$_priceHelper = $this->helper('Ktpl\CategoryView\Helper\Price');
$sortOptions = $block->_getGroupbySortOptions();
?>

<?php $listingBlockItems = $_layoutHelper->getListingBlockItems(); ?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        $sortAttribute = "";
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products <?php /* @escapeNotVerified */ echo $viewMode; ?> items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

            <?php foreach ($sortOptions as $_option): ?>
                <?php if(!empty($_option['value'])):?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php $newSortAttribute = "";?>
                        <?php if($block->_getGroupbySort()):?>
                            <?php 
                                $newSortAttribute = $_dataHelper->getAttributeLabel($_product,$block->_getGroupbySort());?>
                        <?php endif;?>
                        <?php if(trim($newSortAttribute) == trim($_option['label'])):?>
                            <?php if($sortAttribute != $newSortAttribute && !$_product->getIsSaleProduct() && !$_product->getIsNewProduct()):?>
                                <?php $sortAttribute = $newSortAttribute;?>
                                <li class="attribute-group">
                                    <div class="attribute-head">
                                        <span><?php echo __($newSortAttribute);?></span>
                                    </div>
                                </li>
                            <?php endif;?>
                            <?php while(array_key_exists($iterator, $listingBlockItems)): ?>
                                <li class="item product product-item custom-section">
                                <?php echo $_layoutHelper->filterOutputHtml($listingBlockItems[$iterator], $block->getLayout()); ?>
                                </li>
                                <?php $iterator++; ?>
                            <?php endwhile; ?>

                            <?php $iterator++; ?>
                            <li class="item product product-item">
                                <div class="product-item-info" data-container="product-grid">
                                    <?php
                                    $productImage = $block->getImage($_product, $image);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>
                                    <?php // Product Image ?>

                                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
            						
            						<div class="image-container">
                                        <div class="product-labels">
                                            <?php if($_product->getIsNewProduct()): ?>
                                                <div class="label new"><?php /* @escapeNotVerified */ echo __('New'); ?></div>
                                            <?php endif; ?>
                                            <?php if($_product->getIsSaleProduct()): ?>
                                                <div class="label sale"><?php /* @escapeNotVerified */ echo __('Sale'); ?></div>
                                            <?php endif; ?>
                                        </div>

                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                            <?php echo $productImage->toHtml(); ?>                           
                                        </a>
            		                          <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>                                
                               
                            </div>

            						</div>
            						
                                    <div class="product details product-item-details">                            
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link"
                                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                            </a>
                                        </strong>
                                        

                                        <?php if($_product->getTypeId() == \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE): ?>
                							<div class="volume-measurement">
                								<?php /* @escapeNotVerified */ echo $_product->getAttributeText('volume'); ?>
                							</div>
                                        <?php endif; ?>
                                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                        <?php if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE): ?>
                                        	<div class="price-box price-box-range price-final_price">
                                        		<span class="price-container price-final_price tax weee">
                                        			<span id="product-price-<?php echo $_product->getId(); ?>" class="price-wrapper">
                    									<span class="price"><?php echo $_priceHelper->getConfigurableProductPriceRange($_product); ?></span>
                    								</span>
                								</span>
            								</div>
                                     	<?php else: ?>
                                     		<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                        <?php endif; ?>

                                        <?php echo $block->getProductDetailsHtml($_product); ?>

                                         <?php if ($showDescription):?>
                                                <div class="product-item-description">
                                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                    </div>
                                            <?php endif; ?>

                                    </div>
                                </div>
                            </li>
                        <?php endif;?>
                    <?php endforeach; ?>
                <?php endif;?>
            <?php endforeach; ?>
            <?php while(array_key_exists($iterator, $listingBlockItems)): ?>
                <li class="item product product-item custom-section">
                <?php echo $_layoutHelper->filterOutputHtml($listingBlockItems[$iterator], $block->getLayout()); ?>
                </li>
                <?php $iterator++; ?>
            <?php endwhile; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($) {
        $(function(){
            $("body").addClass("<?php echo __('kitchen-appliances');?>");
        })
    });
</script>