<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales v4.x.x
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php if ($this->getCollection() && $this->getCollection()->count()): ?>
	<div class="shops-holder">
		<div class="pps-row">
			<?php if ($this->getBlockTitle()): ?>
				<header>
					<h3><?php echo $this->getBlockTitle(); ?></h3>
				</header>
			<?php endif; ?>

			<section>
				<?php foreach ($this->getCollection() as $event): ?>
					<?php echo $this->getItemHtml($event); ?>
				<?php endforeach; ?>
			</section>
		</div>
	</div>
<?php endif; ?>