<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales v4.x.x
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php foreach ($this->getCollection() as $group): ?>

	<?php if (count($group['items'])): ?>
		<div class="shops-holder">
			<div class="pps-row">
				<header>
					<h3><?php echo $group['name']; ?></h3>
				</header>
				<section>
					<?php foreach ($group['items'] as $item): ?>
						<?php echo $this->getItemHtml($item); ?>
					<?php endforeach; ?>
				</section>
			</div>
		</div>
	<?php endif; ?>

<?php endforeach; ?>
