<div class="admin__fieldset-wrapper-content _hide">
	<form id="text-form" class="form" method="post" autocomplete="off">
	    <fieldset class="admin__fieldset">
			<div class="admin__field _required">
				<label class="admin__field-label" for="text_content">
	    			<span><?php echo __('Content') ?></span>
				</label>
				<div class="admin__field-control">
					<input class="admin__control-text" type="text" name="text_content" id="text_content" data-validate="{required:true}"  />
				</div>
			</div>
			<div class="admin__field">
				<label class="admin__field-label" for="text_css">
	    			<span><?php echo __('Custom CSS') ?></span>
				</label>
				<div class="admin__field-control">
					<input class="admin__control-text" type="text" name="text_css" id="text_css" />
				</div>
			</div>
		</fieldset>
	</form>
</div>