<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-mydetail-addresses">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Address Details') ?></strong>
    </div>
    <div class="block-content">
        <div class="box box-address">
            <div class="box-title-wrapper">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Registered Address') ?></span>
                </strong>
                <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
                    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>" data-ui-id="default-billing-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a>
                <?php endif; ?>
            </div>
            <div class="box-content">
                <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
                    <address>
                        <?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                <?php else: ?>
                    <p><?php /* @escapeNotVerified */ echo __('You have no default billing address in your address book.') ?></p>
                <?php endif; ?>
            </div>
        </div>
        <div class="box box-address">
            <div class="box-title-wrapper">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span>
                </strong>
                <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
                    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>" data-ui-id="default-shipping-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a>
                <?php endif; ?>
            </div>
            <div class="box-content">
                <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
                    <address>
                        <?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                <?php else: ?>
                    <p><?php /* @escapeNotVerified */ echo __('You have no default shipping address in your address book.') ?></p>
                <?php endif ?>
            </div>
        </div>
        <?php if ($_pAddsses = $block->getAdditionalAddresses()): ?>
            <?php foreach ($_pAddsses as $_address): ?>
				<div class="box box-address">
					<div class="box-title-wrapper">
						<strong class="box-title">
							<span><?php /* @escapeNotVerified */ echo __('Additional Address') ?></span>
						</strong>
						<a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/address/edit', ['id' => $_address->getId()]) ?>"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></a>
						<a class="action delete" href="#" role="delete-address" data-address="<?php /* @escapeNotVerified */ echo $_address->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Delete') ?></span></a>
					</div>
					<div class="box-content">
						<address>
							<?php echo $block->getAddressHtml($_address) ?><br />
						</address>
					</div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" role="add-address" title="<?php /* @escapeNotVerified */ echo __('Add New Address') ?>" class="action primary add"><span><?php /* @escapeNotVerified */ echo __('Add New Address') ?></span></button>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            ".block-mydetail-addresses": {
                "address": {
                    "deleteAddress": "div.box-title-wrapper a[role='delete-address']",
                    "deleteUrlPrefix": "<?php /* @escapeNotVerified */ echo $block->getDeleteUrl() ?>id/",
                    "addAddress": "button[role='add-address']",
                    "addAddressLocation": "<?php /* @escapeNotVerified */ echo $block->getAddAddressUrl() ?>"
                }
            }
        }
    </script>

</div>
