<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>

<?php $_helper = $this->helper('\Ktpl\CustomerView\Helper\Data'); ?>
<div class="block block-mydetail-edit">
    
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Personal Details') ?></strong>
    </div>
    <div class="block-content">

        <form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
            
            <?php echo $block->getBlockHtml('formkey')?>
            <?php 
                echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
                    ->setTemplate('Ktpl_CustomerView::account/mydetail/widget/name.phtml')
                    ->setObject($block->getCustomer())->toHtml() 
            ?>

            <?php 
                $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') 
                    ->setTemplate('Ktpl_CustomerView::account/mydetail/widget/dob.phtml');
            ?>

            <div class="field contact_number required">
                <div class="field-display">
                    <label class="label">
                        <span><?php /* @escapeNotVerified */ echo __('Contact Number') ?></span>
                    </label>
                    <div class="control">
                        <label class="value"><?php echo $block->escapeHtml($_helper->getCustomerAttributeValue($this->getCustomer()->getId(), 'contact_number')); ?></label>
                    </div>
                    <div class="field-edit">
                        <a href="#" class="edit-field"><?php echo __('Edit') ?></a>
                    </div>
                </div>
                <div class="field-actual">
                    <label class="label" for="contact_number">
                        <span><?php /* @escapeNotVerified */ echo __('Contact Number') ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="contact_number" id="contact_number" value="<?php echo $block->escapeHtml($_helper->getCustomerAttributeValue($this->getCustomer()->getId(), 'contact_number')); ?>" title="<?php /* @escapeNotVerified */ echo __('Contact Number') ?>" class="input-text" />
                    </div>
                    <div class="field-edit">
                        <a href="#" class="save-field"><?php echo __('Save') ?></a>
                        <a href="#" class="cancel-field"><?php echo __('Cancel') ?></a>
                    </div>
                </div>
            </div>

            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>

            <div class="field email required">
                <div class="field-display">
                    <label class="label">
                    	<span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
                	</label>
                    <div class="control">
                        <label class="value"><?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?></label>
                    </div>
                    <div class="field-edit">
                        <a href="#" class="edit-field"><?php echo __('Edit') ?></a>
                        <div class="choice">
                            <input type="hidden" name="change_email" id="change-email" value="0" title="<?php /* @escapeNotVerified */ echo __('Change Email') ?>" />
                        </div>
                    </div>
                </div>
                <div class="field-actual">
                    <label class="label" for="email">
                    	<span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
                    </label>
                    <div class="control">
                        <input type="email" name="email" id="email" autocomplete="email" value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
                    </div>
                    <div class="field-edit">
                        <a href="#" class="save-field"><?php echo __('Save') ?></a>
                        <a href="#" class="cancel-field"><?php echo __('Cancel') ?></a>
                    </div>
                </div>
                <div class="field-actual current-password-email">
                </div>
            </div>



            <div class="field new password required">
                <div class="field-display">
                    <label class="label">
                        <span><?php /* @escapeNotVerified */ echo __('Password') ?></span>
                    </label>
                    <div class="control">
                        <label class="value">********</label>
                    </div>
                    <div class="field-edit">
                        <a href="#" class="edit-field"><?php echo __('Edit') ?></a>
                        <div class="choice">
                            <input type="hidden" name="change_password" id="change-password" value="0" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>" />
                        </div>
                    </div>
                </div>
                <div class="field-actual current-password-password">
                    <div class="field-edit">
                        <a href="#" class="save-field"><?php echo __('Save') ?></a>
                        <a href="#" class="cancel-field"><?php echo __('Cancel') ?></a>
                    </div>
                </div>
                <div class="field-actual" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
                    <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password') ?></span></label>
                    <div class="control">
                        <input type="password" class="input-text" name="password" id="password"
                            data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                            data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                            data-input="new-password"
                            data-validate="{required:true, 'validate-customer-password':true}"
                            autocomplete="off" />
                        <div id="password-strength-meter-container" data-role="password-strength-meter" >
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                                    <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                                </span>
                            </div>
                        </div>
                    </div>                    
                </div>
                <div class="field-actual">
                    <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password') ?></span></label>
                    <div class="control">
                        <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-input="confirm-password" autocomplete="off" />
                    </div>
                </div>
            </div>

        </form>

        <div class="current-password-wrapper">
            <div id="current-password-template">
                <label class="label" for="current-password-password"><span><?php /* @escapeNotVerified */ echo __('Current Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="current_password" id="current-password" autocomplete="off" data-validate="{required:true}" />
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

        $(".edit-field").click(function(e) {
            e.preventDefault();

            $(this).closest('.field').find('.field-display').hide();
            $(this).closest('.field').find('.field-actual').show();

            var changeEmail = $(this).closest('.field').find('#change-email');
            if($(changeEmail).val() != undefined) {
                $(changeEmail).val(1);
                $("#current-password-template").appendTo(".current-password-email");
            }

            var changePassword = $(this).closest('.field').find('#change-password');
            if($(changePassword).val() != undefined) {
                $(changePassword).val(1);
                $("#current-password-template").prependTo(".current-password-password");
                $("#password-confirmation").attr('data-validate', "{required:true, equalTo:'[data-input=new-password]'}");
            }
        });

        $(".cancel-field").click(function(e) {
            e.preventDefault();

            $(this).closest('.field').find('.field-display').show();
            $(this).closest('.field').find('.field-actual').hide();

            var changeEmail = $(this).closest('.field').find('#change-email');
            if($(changeEmail).val() != undefined) {
                $(changeEmail).val(0);
                $("#current-password-template").appendTo(".current-password-wrapper");
            }

            var changePassword = $(this).closest('.field').find('#change-password');
            if($(changePassword).val() != undefined) {
                $(changePassword).val(0);
                $("#current-password-template").appendTo(".current-password-wrapper");
                $("#password-confirmation").removeAttr('data-validate', "{required:true}");
            }
        });

        $(".save-field").click(function(e) {
            e.preventDefault();
            $('.form-edit-account').submit();
        });
    });
</script>