<?php /**
 * Copyright © 2016 ktpl (http://www.ktpl.co/) All rights reserved.
 */
?>
<?php $_items = $block->getSliderProductsCollection() ?>
<?php if(count($_items)==0) : ?>
<?php return  ?>
<?php endif ?>

<?php $_helper = $this->helper('Magento\Catalog\Helper\Output') ?>
<?php $sliderId = $block->getSliderDisplayId() ?>
<?php $slider = $block->getSlider()  ?>

<?php $image = 'category_page_grid' ?>
<?php $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW ?>
<?php $viewMode = 'grid' ?>
<?php $class = $slider->getType() ?>
<?php $type = "" ?>
<?php $showWishlist = $slider->getDisplayWishlist() ?>
<?php $showCompare = $slider->getDisplayCompare() ?>
<?php $showCart = $slider->getDisplayCart() ?>
<div class="block block-product-slider slider-list <?php /* @escapeNotVerified */ echo $class; ?>" <?php echo $slider->getRtl() ? 'dir="rtl" ' : "" ?> >
    <?php if($slider->getDisplayTitle()): ?>
        <div class="block-title-main">
            <h2 id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $slider->getTitle() ?></h2>
        </div>
    <?php endif ?>
    <div id="loading" style="text-align: center; padding:40px 0 40px 0">
        <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
             alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
             >
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading" style="display:none">
        <?php if(!empty($_items)): ?>
            <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <div class="products list items product-slider<?php echo $sliderId ?> owl-carousel">
                <?php foreach($_items as $collection): ?>
                    <?php $iterator = 1; ?>
                    <?php foreach ($collection as $_item): ?>

                <div class="item product product-item-carousel">
                    <div class="product-item-info<?php echo $slider->getGrid() ? '' : '-'.$class ?> product-item-info">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
                        </strong>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                        
                        <?php if($slider->getDisplayPrice()): ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                        <?php endif ?>
                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                    <?php endforeach ?>
                <?php endforeach ?>
            </div>
        </div>
        <?php endif ?>
    </div>
</div>

<?php if(!$slider->getGrid()): ?>
<script>
    require([
        'jquery',
        'owlcarousel',
        'domReady!'
    ], function ($) {
        $('.product-slider'+<?php echo $sliderId ?>).owlCarousel({
            "nav": true,
			pagination:false,
            dots: <?php echo var_export((bool)$slider->getNavigation()) ?>,
            loop: <?php echo var_export((bool)$slider->getInfinite()) ?>,
            items:4,
            autoplay: <?php echo var_export((bool)$slider->getAutoplay()) ?>,
            margin: 0,
            center: false,
            autoplaySpeed: <?php echo $slider->getAutoplaySpeed() ?>, 
			 responsive : {
                // breakpoint from 0 up
                0 : {
                    items:1,
                    nav:true
                },
                320 : {
                    items:1,
                    nav:true
                },
				640 : {
                    items:2,
                    nav:true
                },
                768 : {
                    items:3,
                    nav:true
                },
                1199 : {
                    items:4,
                    nav:true
                }
            },

        });
            $(".block-product-slider .block-content").css("display","block");
            $(".block-product-slider #loading").css("display","none");
    })

</script>
<?php endif ?>

