<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $_product = $block->getProduct();?>
<?php $_total = $block->getItems()->getSize() ?>
<?php if ($_total): ?>
    <div class="table-wrapper comparison">
		<div class="block-title title">
			<strong><?php /* @escapeNotVerified */ echo __('Compare and pick the one that best suits your needs'); ?></strong>
		</div>
        <div class="data table table-comparison" id="current-product-comparison"
            data-mage-init='{"compareList":{
                "windowPrintSelector":".action.print",
                "productsInRow":"1",
                "selectors":{
                    "productAddToCartSelector":"button.action.tocart"}
            }}'>
           
			<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
			<div class="cell product attribute">
			<?php foreach ($block->getItems() as $_item): ?>
				<?php if($_product->getId() == $_item->getEntityId()):?>
						<a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
						<?php echo $block->getImage($_item, 'product_comparison_list')->toHtml(); ?>
						</a>
						<strong class="product-item-name">
							<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
							<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
							</a>
						</strong>
						<!-- <strong class="product-features"> -->
                                    <?php /* @escapeNotVerified */ // echo __('Features'); ?>
                               <!--  </strong> -->
						<?php echo $block->getReviewsSummaryHtml($_item, 'short') ?>
						<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item, '-compare-list-top') ?>
						<div class="product-item-actions">
							<div class="actions-primary">
							<?php if ($_item->isSaleable()): ?>
								<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>" method="post">
									<?php echo $block->getBlockHtml('formkey')?>
									<button type="submit" class="action tocart primary">
										<span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
									</button>
								</form>
							<?php else: ?>
								<?php if ($_item->getIsSalable()): ?>
									<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
								<?php else: ?>
									<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
								<?php endif; ?>
							<?php endif; ?>
							</div>
							<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
								<div class="secondary-addto-links actions-secondary" data-role="add-to-links">
									<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist">
									<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
									</a>
								</div>
							<?php endif; ?>
						</div>
						<table class="compare-products-attributes">
							<tbody>
                            <?php $attrCount = count($block->getAttributes());?>
                            <?php $iterator = 0;?>
							<?php foreach ($block->getAttributes() as $_attribute): ?>
                                <?php $iterator++;?>
								<tr>
									<span class="attribute label">
										<?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())) ?>
									</span>
									<div class="attribute value <?php echo $countAttr = ($iterator == $attrCount)? "last":""?>">
									<?php switch ($_attribute->getAttributeCode()) {
										case "price": ?>
											<?php
												/* @escapeNotVerified */ echo $block->getProductPrice(
													$_item,
													'-compare-list-' . $_attribute->getCode()
												)
											?>
											<?php break;
										case "small_image": ?>
											<?php $block->getImage($_item, 'product_small_image')->toHtml(); ?>
											<?php break;
										default: ?>
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
										<?php break;
									} ?>
									</div>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>
				<?php endif;?>                            
			<?php endforeach; ?>
			</div>                
        </div>
		
        <div class="data table table-comparison slider" id="product-comparison"
            data-mage-init='{"compareList":{
                "windowPrintSelector":".action.print",
                "productsInRow":"5",
                "selectors":{
                    "productAddToCartSelector":"button.action.tocart"}
            }}'>
				<ul id="comaprison-silder" class="owl-carousel">
				<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>					
                    <?php foreach ($block->getItems() as $_item): ?>
                        <?php if($_product->getId() != $_item->getEntityId()):?>						
                            <li class="cell product attribute items">
                               <div class="test" style="position:relative;">
                                    <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                                        <?php echo $block->getImage($_item, 'product_comparison_list')->toHtml(); ?>
                                    </a>
                                    <div data-item-id="<?php echo $_item->getEntityId()?>" class="compare-product-expand-collapse active" data-expand="true">
                                        <?php echo __("expand");?></div>
                                </div>

                                <strong class="product-item-name">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
                                    </a>
                                </strong>
								<div id="<?php echo __("compare-item-id-") . $_item->getEntityId();?>" class="features-data compare-item-id<?php echo $_item->getEntityId();?>">
    								<!-- <strong class="product-features">
                                        <?php /* @escapeNotVerified */ // echo __('Features'); ?>
                                    </strong> -->
                                    <?php echo $block->getReviewsSummaryHtml($_item, 'short') ?>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item, '-compare-list-top') ?>
                                    <div class="product-item-actions">
                                        <div class="actions-primary">
                                        <?php if ($_item->isSaleable()): ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>" method="post">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit" class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        </div>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <table class="compare-products-attributes">
                                        <tbody>
                                            <?php $attrCount = count($block->getAttributes());?>
                                            <?php $iterator = 0;?>
                                        <?php foreach ($block->getAttributes() as $_attribute): ?>
                                            <?php $iterator++;?>
                                            <tr>
                                                <span class="attribute label">
                                                    <?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())) ?>
                                                </span>
                                                <div class="attribute value <?php echo $countAttr = ($iterator == $attrCount)? "last":""?>">
                                                <?php switch ($_attribute->getAttributeCode()) {
                                                    case "price": ?>
                                                        <?php
                                                            /* @escapeNotVerified */ echo $block->getProductPrice(
                                                                $_item,
                                                                '-compare-list-' . $_attribute->getCode()
                                                            )
                                                        ?>
                                                        <?php break;
                                                    case "small_image": ?>
                                                        <?php $block->getImage($_item, 'product_small_image')->toHtml(); ?>
                                                        <?php break;
                                                    default: ?>
                                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                                    <?php break;
                                                } ?>
                                                </div>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="explore-product">
                                    <a class="explore-btn" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo __("explore product") ?>">
                                    <?php /* @escapeNotVerified */ echo __("Explore Product") ?>
                                    </a>
                                </div>
                            </li>						
                        <?php endif;?>                            
                    <?php endforeach; ?>                
				</ul>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    require(['jquery', 'OwlCarousel'], function($){
        $(function(){
			$('#comaprison-silder').owlCarousel({
				"autoplay": false,				
				"items": 3,
                "dots": false,
				"margin": 30,
				"nav": true,
				"loop": true,
				"center":false,
				"responsive":
				{
					
					1200:{
						items:3
					},
                    767:{
                        items:2
                    },
                    240:{
                        items:1
                    }
				}
			});

            $(document).on("click", ".compare-product-expand-collapse", function(){              
                var compateId = $(this).attr("data-item-id");
                $(this).parent().parent().find('.features-data').toggle();              
                $(this).toggleClass('active');              
            });            
        })
    });
</script>
