<?php
/**
 * Blog post list item template
 *
 * @var $block \Ktpl\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_helper = $this->helper('Ktpl\Blog\Helper\Data');
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <div class="post-content">
        <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-ftimg-hld">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </a>
                <?php 
                $url =  $block->getUrl('blog/index/wishlist',[
                            'postid' => $_post->getId(),
                            '_secure' => $block->getRequest()->isSecure()
                        ]); 
                ?>
                <?php if($_helper->isWishlisted($_post->getId())):?>
                    <a class="save-article-link save-link" href="<?php echo $url; ?>" data-id="<?php echo $_post->getId() ?>" title="<?php echo __('Read %1',$_postName) ?>">
                    <?php echo __('&#x2661;') ?>
                <?php endif;?>
            </a>
            </div>
            <?php } ?>
			<h2 class="post-title">
                <a class="post-item-link"
                   href="<?php echo $_postUrl ?>">
                    <?php echo $_postName; ?>
                </a>
            </h2>
            <div class="post-text-hld clearfix">
                <?php echo $block->getShorContent() ?>
            </div>            
        </div>
    </div>    
</li>