<?php
/**
 * Blog post next and prev post links
 *
 * @var $block \Ktpl\Blog\Block\Post\View\NextPrev
 */
?>

<?php if ($block->displayLinks()) { ?>
    <?php
        $prevPost = $this->getPrevPost();
        $nextPost = $this->getNextPost();
    ?>
    <?php if ($prevPost || $nextPost) { ?>
        <div class="post-nextprev-hld clearfix">
            <?php $title = $block->escapeHtml($prevPost->getTitle()) ?>
            <?php if ($prevPost) { ?>
                <a class="nextprev-link prev-link" href="<?php echo $prevPost->getPostUrl() ?>" title="<?php echo __('Read %1',$title) ?>">
                    <?php echo __('&#x003C;  Previous') ?>
                </a>
            <?php } ?>
            <a class="share-article-link share-link" href="<?php echo $block->getPost()->getPostUrl() ?>" data-id="<?php echo $block->getPost()->getId() ?>" title="<?php echo __('Read %1',$title) ?>">
                <?php echo __('Share this article') ?>
            </a>

            <a class="save-article-link save-link" href="<?php echo $block->getActionUrl(); ?>" data-id="<?php echo $block->getPost()->getId() ?>" title="<?php echo __('Read %1',$title) ?>">
                <?php echo __('&#x2661;  Save this article') ?>
            </a>

            <?php if ($nextPost) { ?>
                <?php $title = $block->escapeHtml($nextPost->getTitle()) ?>
                <a class="nextprev-link next-link" href="<?php echo $nextPost->getPostUrl() ?>" title="<?php echo __('Read %1',$title) ?>">
                    <?php echo __('Next &#x003E;') ?>
                </a>
            <?php } ?>
        </div>
    <?php } ?>
<?php } ?>
