<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales v4.x.x
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<div id="privatesale-event-init"></div>
<script type="text/x-magento-init">
    {
        "#privatesale-event-init": {
        	"privatesaleEvent": {
	            "timeUrl": "<?php echo $this->getUrl('prprivatesale/ajax/timeAction'); ?>",
	            "previewDate": "<?php echo $block->getPreviewDate(); ?>",
	            "previewMode": "<?php echo $block->getPreviewMode(); ?>",
	            "countdownLabelsFew": "<?php echo __('years,months,weeks,days,hours,minutes,seconds'); ?>",
				"countdownLabelsOne": "<?php echo __('year,month,week,day,hour,minute,second'); ?>"
			}
        }
    }
</script>

<script type="text/javascript">
	 var privateSaleEventData = {};
</script>

<div id="privatesale-homepage-init"></div>
<script type="text/x-magento-init">
    {
        "#privatesale-homepage-init": {
            "privatesaleHomepage": {}
        }
    }
</script>
