<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_dataHelper = $this->helper('Ktpl\CategoryView\Helper\Data');
$_layoutHelper = $this->helper('Ktpl\CategoryView\Helper\Layout');
?>
<?php $listingBlockItems = $_layoutHelper->getListingBlockItems(); ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $viewMode = "list"
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>        
        <ol class="products <?php /* @escapeNotVerified */ echo $viewMode; ?> items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php while(array_key_exists($iterator, $listingBlockItems)): ?>
                    <li class="product-item-kit custom-section">
                    <?php echo $_layoutHelper->filterOutputHtml($listingBlockItems[$iterator], $block->getLayout()); ?>
                    </li>
                    <?php $iterator++; ?>
                <?php endwhile; ?>

                <?php $iterator++; ?>
                <li class="product-item-kit">
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                            $product = $_dataHelper->getCurrentProduct($_product->getId());
                        ?>

                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                         <div class="product-labels">
                                <?php if($_product->getIsNewProduct()): ?>
                                    <div class="label new"><?php /* @escapeNotVerified */ echo __('New'); ?></div>
                                <?php endif; ?>
                                <?php if($_product->getIsSaleProduct()): ?>
                                    <div class="label sale"><?php /* @escapeNotVerified */ echo __('Sale'); ?></div>
                                <?php endif; ?>
                            </div>
                        <div class="product-item-container">
                            <?php 
                            $productImages = $_dataHelper->getGalleryImages($product);
                            $imgUrl = "";
                            $imageCount = 0;
                            $smallImageCount = 0;
                            ?>
                            <?php foreach ($productImages as $image): ?>
                                <?php if($image->getHidefromlisting() != 1 && $image->getIsbigimage() != 1 && $image->getFile() != $image->getFullImage()):?>
                                    <?php $smallImageCount++;?>
                                <?php endif;?>
                            <?php endforeach ?>   
                            <?php foreach ($productImages as $image):?>
                                <?php if($image->getIsbigimage() == 1): ?>
                                    <?php $imgUrl = $image->getLargeImageUrl();?>
									<div class="big-image">
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" tabindex="-1">
										   <img class="product-image-photos" src="<?php echo $imgUrl;?>" alt="Party Starter Kit"/>
                                        </a>
									</div>
                                <?php elseif ($image->getFile() == $image->getFullImage()):?>         <?php $imgUrl = $image->getLargeImageUrl();?>
                                    <div class="full-image">
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <img class="product-image-photos" src="<?php echo $imgUrl;?>" alt="Party Starter Kit"/>
                                        </a>
                                    </div>
                                <?php elseif(!$image->getHidefromlisting()):?>                           
                                    <?php $imgUrl = $image->getMediumImageUrl();?>
                                    <?php $imageCount++;?>
									<div class="small-image <?php echo $imageLastClass = ($imageCount == $smallImageCount)? 'last' : ''?>">
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										    <img class="product-image-photos" src="<?php echo $imgUrl;?>" alt="Party Starter Kit"/>
                                        </a>
									</div>
                                <?php endif;?>                 
                            <?php endforeach;?>
                            <div class="grouped-product-options-info">  
							<div class="grouped-product-options-inner">	
                              
                             <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            							
								<div class="product grouped-product-pieces">
								   <?php 
										$associatedProducts = $_dataHelper->getGroupedProducts($_product);
										foreach ($associatedProducts as $items):?>
								   <?php /* @escapeNotVerified */ echo count($items)  ?>
								   <?php echo $retVal = (count($items) == 1) ? "piece" : "pieces" ;?>
										<?php endforeach;?>
								</div>
								<div class="product description product-item-description">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								</div>
								<div class="info-product-item-link">
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo __('Explore This Starter Kit'); ?>
                                </a>
                            </div>
                            </div>                            
							</div>                            
                        </div>                          

                       <!--  <div class="product details product-item-details">                            
                            <?php // echo $block->getReviewsSummaryHtml($_product, $templateType); ?>                            
                            <?php // echo $block->getProductDetailsHtml($_product); ?>
                        </div> -->

                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($) {
        $(function(){
            $("body").addClass("<?php echo __('category-starter-kit');?>");
        })
    });
</script>
